name: Test2 
on:
  workflow_call:
    inputs:
        branch:
          required: false
          default: ''
          type: string
  
jobs:
  build:
    name: Run API
    runs-on: ubuntu-latest
    steps:
      - name: Build API
        run: |
          echo "Build API"
          sleep 10s
